### ISSUE TITLE
Generate .ics files for consultation

### ISSUE THREAD

**Issue by Tschonti** [kir-dev/konzisite-api#114]
Users should be able to download a `.ics` calendar invite file for every consultation they joined and import it into their calendar. It was implemented in TanulóSCH, maybe you can see how it's implemented there. 
Recommended library: https://www.npmjs.com/package/ics

**Comment by Frigyes309** [comment]
I'd like to take this issue.

**Comment by Tschonti** [comment]
You can just assign it to yourself in the future
