### ISSUE TITLE
Add support for subscribing to subjects and groups

### ISSUE THREAD

**Issue by Tschonti** [kir-dev/konzisite-api#116]
Users should be able to subscribe to subjects and groups, so eventually they would be notified via email if a new consultation has been added to that subject/group. (the email sending is not part of this issue!)

Schema changes:
- UserToGroup should have an `isSubscribed` field (defaults to false)
- New (implicit) many-to-many relations between subjects and users, representing subject subscription. [Prisma help](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#implicit-many-to-many-relations)

New endpoints:
- POST  `/groups/:id/subscribe` - check if the user is a member of that group and set the `isSubscribed` field to true
- POST `/groups/:id/unsubscribe` - check if the user is a member of that group and set the `isSubscribed` field to false

- POST `/subjects/:id/subscribe` - add a new record to the implicit relationship (if it doesn't exist already)
- POST `/subjects/:id/unsubscribe` - remove the record representing this subscription from the implicit relationship (if it exists)

Any signed-in user should have permission to use these endpoints

**Comment by Frigyes309** [comment]
I'd like to challenge myself with this Issue.
