### ISSUE TITLE
Nest v10 migration issue with FileValidator

### ISSUE THREAD

**Issue by Tschonti** [kir-dev/konzisite-api#251]
When the project was migrated to nest v10, the `Express.File.Multer` type was no longer allowed in the `isValid` method of a class extending `FileValidator`.
An issue was opened: https://github.com/nestjs/nest/issues/11803
And they said to have fixed it in: https://github.com/nestjs/nest/pull/11822
But the problem remained in our repo. So I just used any instead of the express type, it works just the same and we won't extend that method anyway. If anyone wants to dig deeper, or they release another fix, feel free to fix it in our project.

This occurs in `src/utils/FileMaxSizeValidator.ts` and `src/utils/FileExtensionValidator.ts`

**Comment by takanome-dev** [comment]
Hey @Tschonti, regarding this issue, see https://github.com/nestjs/nest/issues/11803#issuecomment-1635561921

**Comment by Tschonti** [comment]
resolved with nest v10.1, updated the project in https://github.com/kir-dev/konzisite-api/commit/631572ebab2e558a52259b6de553173de9e5c375
