### ISSUE TITLE
Create subject DTOs and rework endpoints

### ISSUE THREAD

**Issue by Tschonti** [kir-dev/konzisite-api#51]
Creating and editing subjects from the frontend is not a priority right now, but eventually admins should be able to create and edit subjects with forms. Things to implement on the backend for this:

- create DTOs with validation for creating and updating subjects, use these instead of the Prisma types
- ~add a role field to users~
- ~make sure that only Admins can use the subject endpoints (using #54)~ Done in #63
- ~optionally create endpoints for promoting users to admin~

**Comment by nmate980829** [comment]
I think the "add a role field to users" and "optionally create endpoints for promoting users to admin" bulletpoints are not in scope for this issue. It is better related to issue #54

**Comment by Tschonti** [comment]
Adding role to users is not that important right now, it can be done later, when it's needed for subject creation. But you're right, it should probably be a separate issue.
