### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by Tschonti** [kir-dev/konzisite-api#54]
Right now any logged in user can edit and delete any resources in the DB. Do some research about the standard way of authorizing users in endpoints and return 403 if they don't have access to the route.

**Comment by Badrri-Narayanan** [comment]
Hi, I would like to work on this issue. Can you please assign it to me?

**Comment by nmate980829** [comment]
> Hi, I would like to work on this issue. Can you please assign it to me?

Hi! Since this feature is part of the core functionality of the project we'd like to assign it to someone inside our organization. Thank you for your inquiry!
