### ISSUE TITLE
Group controller new endpoints

### ISSUE THREAD

**Issue by Tschonti** [kir-dev/konzisite-api#65]
- [x] - POST /:id/leave - this should delete the `UserToGroup` entity even if it's in the pending state
- [x] - POST /:id/approve/:userid
- [x] - POST /:id/decline/:userid

these are low prio:

- [x] - POST /:id/promote/:userid
- [x] - POST /:id/demote/:userid

**Comment by abhishekkumar11724** [comment]
could you provide little bit more details or at least elaborate what endpoint function will do ??
it will be helpful !!!!

**Comment by Tschonti** [comment]
Since this feature is part of the core functionality of the project, this issue will be assigned to one of our members and they'll know what to do. Thank you for your inquiry!
